public void DamageNPC(Player myPlayer,NPC npc, ref int damage, ref float knockback){
    if (npc.name=="Skeleton") damage *= 4;
    else if (npc.name=="Armored Skeleton") damage *= 4;
    else if (npc.name=="Heavy Skeleton") damage *= 4;
    else if (npc.name=="Big Boned") damage *= 4;
    else if (npc.name=="Angry Boned") damage *= 4;
    else if (npc.name=="Short Boned") damage *= 4;
    else if (npc.name=="Bone Serpent") damage *= 4;
    else if (npc.name=="Big Boned") damage *= 4;
    else if (npc.name=="Cursed Skull") damage *= 4;
    else if (npc.name=="Dark Caster") damage *= 4;
    else if (npc.name=="Dungeon Guardian") damage *= 4;
    else if (npc.name=="Zombie") damage *= 4;
    else if (npc.name=="Bald Zombie") damage *= 4;
    else if (npc.name=="Mummy") damage *= 4;
    else if (npc.name=="Light Mummy") damage *= 4;
    else if (npc.name=="Dark Mummy") damage *= 4;
    else if (npc.name=="Possessed Armor") damage *= 4;
    else if (npc.name=="Wraith") damage *= 4;
    else if (npc.name=="Undead Miner") damage *= 4;
    else if (npc.name=="Doctor Bones") damage *= 4;
    else if (npc.name=="The Groom") damage *= 4;
    else if (npc.name=="Skeletron") damage *= 4;
    else if (npc.name=="Skeleton Archer") damage *= 4;
    else if (npc.name=="Tim") damage *= 4;
    else if (npc.name=="Omnirs Vampire") damage *= 4;
    else if (npc.name=="Omnirs The Earth Fiend Lich") damage *= 4;
    else if (npc.name=="Omnirs Rotting Ghoul") damage *= 4;
    else if (npc.name=="Omnirs Crypt Shambler") damage *= 4;
}